language: php

sudo: false

dist: trusty

install:
  - travis_retry composer require phpunit/phpunit:^7.5

jobs:
  include:
   - php: 5.3 # Composer and PHPUnit require PHP 5.3.2+ to run, so we cannot test below 5.3
     dist: precise # PHP 5.3 is supported only on Precise.
     install: travis_retry composer require phpunit/phpunit:^4.8
   - php: 5.4
     install: travis_retry composer require phpunit/phpunit:^4.8
   - php: 5.5
     install: travis_retry composer require phpunit/phpunit:^4.8
   - php: 5.6
     install: travis_retry composer require phpunit/phpunit:^5.7
   - php: 7.0
     install: travis_retry composer require phpunit/phpunit:^6.5
   - php: 7.1
   - php: 7.2
   - php: 7.3
   - php: 7.4
   - php: nightly
  fast_finish: true
  allow_failures:
   - php: nightly

services:
  - memcached
  - mysql

before_script:
    - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
    - phpenv config-rm xdebug.ini || return 0

script:
   - ./phpunit.sh
