language: php
os: linux
dist: xenial

install:
  - travis_retry composer install

jobs:
  include:
   - php: 7.2
   - php: 7.3
   - php: 7.4
   - php: 8.0
     install: travis_retry composer config platform.php 7.4.0 && composer install
  fast_finish: true

services:
  - memcached
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
  - phpenv config-rm xdebug.ini || return 0

script:
  - ./phpunit.sh
